### ISSUE TITLE
textsc não funciona pra lualatex e xelatex

### ISSUE THREAD

**Issue by malbarbo** [lordantonelli/thesis-model-icmc#1]
Ao usar o comando `\textsc` o lualatex e o xelatex gera um texto normal, e não com small caps. O pdflatex funciona corretamente. No log o seguinte warning parece ser relevante

```
LaTeX Font Warning: Font shape `EU1/LatinModernRoman(0)/m/sc' undefined
(Font)              using `EU1/LatinModernRoman(0)/m/n' instead on input line 1
38.
```

Eu tentei de muitas forma arrumar este problema mas não consegui. Este é um problema da classe icmc, o seguinte código funciona corretamente.

``` latex
\documentclass[brazil,12pt]{abntex2}
\usepackage{lmodern}
\usepackage{fontspec}

\begin{document}
\textsc{Text}
\end{document}
```

O seguinte código não funciona corretamente com o lualatex e o xelatex

``` latex
\documentclass[english, brazil]{packages/icmc}

\tituloPT{x}
\autor{x}
\orientador{x}

\begin{document}
\textsc{Text}
\end{document}
```

**Comment by lordantonelli** [comment]
Correção implementada na versão 1.2.5.
Obrigado pela colaboração.

**Comment by lordantonelli** [comment]
Correção implementada na versão 1.2.5.
Obrigado pela colaboração.
