### ISSUE TITLE
\autoref apresenta texto em Espanhol

### ISSUE THREAD

**Issue by msmello** [lordantonelli/thesis-model-icmc#3]
Quando utilizado o comando \autoref o texto é mostrado em espanhol ao invés de português. Por exemplo:
Equação -> Equación
Tabela -> Tabla

Pode ser algum erro de configuração do meu lado?

**Comment by lordantonelli** [comment]
Como está definido seu: `\documentclass`?

**Comment by msmello** [comment]
\documentclass[mestrado, pre-defesa]{packages/icmc}

**Comment by lordantonelli** [comment]
Em algum local do seu arquivo foi definido algo para ser utilizado em espanhol?

**Comment by msmello** [comment]
Não, deixei na configuração padrão pois desejo utilizar somente pt e en.

**Comment by lordantonelli** [comment]
Poderia me enviar um e-mail para conversarmos melhor?
humberto.antonelli@gmail.com

**Comment by lordantonelli** [comment]
Bug corrigido na Versão 1.3.4.
