### ISSUE TITLE
List of algorithms in EN has items named in PT-Br

### ISSUE THREAD

**Issue by damascenodiego** [lordantonelli/thesis-model-icmc#5]
When the thesis language is set to **EN**, the items at the **List of Algorithms** should be named as _Algorithm n_ where _n_ is the number of the algorithm.
However, the items are named as "Algoritmo". 
To correct this issue, the 'Algoritmo' string should be replaced by **\algoritmoname**

See the line bellow where this bugfix should be placed.

https://github.com/lordantonelli/thesis-model-icmc/blob/a6ed851ab1068dacba93758e9afb72b1c7498bf2/packages/icmc.cls#L751

**Comment by lordantonelli** [comment]
Thank you for your contribution.

This issue was fixed in the version 1.3.7.
Please, update your template.
