### ISSUE TITLE
Class memoir Warning

### ISSUE THREAD

**Issue by CShulby** [lordantonelli/thesis-model-icmc#6]
./packages/icmc.cls: Class memoir Warning: You are using the caption package with the memoir class. To prepare we will now reset all captioning macros and configurations to kernel defaults, and then let the caption package take over. Please remember to use the caption package interfaces in order to configure your captions.

**Comment by lordantonelli** [comment]
Hi, 

This is just a warning due to package clonfict. It is not important and does not cause compilation problems.

[]'s
