### ISSUE TITLE
Glossaries Problem

### ISSUE THREAD

**Issue by leomaurodesenv** [lordantonelli/thesis-model-icmc#7]
Hello, I started to use this model, but I had a little problem with glossaries.

I used the set commands:
```
\input{tex/glossario}
\glsaddall % Comando para incluir todas as definições
\printglossaries % Impressão do glossário
```
and add new words by this command in `text/glossario.tex`  
`\newword{}{}`   
but the new words don't compile.

**Comment by lordantonelli** [comment]
Hi,

Which LaTex editor are you using to compile?
The "glossario.tex" file is inside "text" folder?


[]'s

**Comment by leomaurodesenv** [comment]
Thanks for fast answer.
I had a mistake. The right folder: `tex`, so the file is `tex/glossario.tex`.
I try used TeXstudio and [ShareLatex](https://pt.sharelatex.com/)

**Comment by leomaurodesenv** [comment]
Problem "Fixed".. only need to clean the cache to reload the `glossario.tex`.
